/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query analytics — volume, intent + route distribution, failures */
        get: operations["analytics_api_v1_admin_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every document indexed in the vector store */
        get: operations["list_documents_api_v1_admin_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a document and ingest it into the corpus (admin-only) */
        post: operations["upload_document_api_v1_admin_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/documents/{source}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-source detail with full version history */
        get: operations["document_detail_api_v1_admin_documents__source__get"];
        put?: never;
        post?: never;
        /** Delete every chunk for a source */
        delete: operations["delete_document_api_v1_admin_documents__source__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/evaluation/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Past evaluation runs, most recent first (cursor-paginated)
         * @description List evaluation runs, newest first.
         *
         *     Pagination uses an ID cursor (cheap, monotonic, immune to the same
         *     ``created_at`` collisions that can break offset pagination on
         *     SQLite). The response includes ``next_cursor`` when more rows exist;
         *     a ``null`` ``next_cursor`` means the caller has reached the end.
         */
        get: operations["list_evaluation_runs_api_v1_admin_evaluation_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/evaluation/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single evaluation run with full per-row report */
        get: operations["get_evaluation_run_api_v1_admin_evaluation_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Delete one evaluation run */
        delete: operations["delete_evaluation_run_api_v1_admin_evaluation_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Headline metrics for the admin dashboard Overview page */
        get: operations["overview_api_v1_admin_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System health snapshot for the admin dashboard */
        get: operations["system_health_api_v1_admin_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login restricted to admin accounts */
        post: operations["admin_login_api_v1_auth_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the current user's password (requires current password)
         * @description Change the authenticated user's password.
         *
         *     Requires the current password as proof-of-possession. On success
         *     every active refresh token is revoked (the user is forced to log
         *     in again on other devices) and the current refresh cookie is
         *     cleared. The access token survives until expiry — fixing that
         *     requires a JWT denylist, which is intentionally out-of-scope.
         */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email + password (any role) */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh token and clear the cookie */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange refresh cookie for a new access token (rotates refresh) */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/ingest-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch a legal web page and extract clean article text
         * @description Direct URL ingestion: fetch + extract main article text.
         *
         *     Boilerplate (nav, ads, related stories) is removed by trafilatura;
         *     only the substantive page body is kept. The response uses the same
         *     :class:`_UploadResponse` shape as file upload — ``stored_as`` is the
         *     final URL (after redirects) since no file is persisted on disk. The
         *     final URL also doubles as the versioning source identifier when
         *     ``persist=true``.
         */
        post: operations["ingest_url_api_v1_documents_ingest_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload and extract text from a legal document */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ingested versions of a document (newest, active first) */
        get: operations["list_document_versions_api_v1_documents_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a CSV test set through LawFlow and score it */
        post: operations["run_evaluation_api_v1_evaluation_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/run-async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue a CSV evaluation as a background job; returns the job id
         * @description Background-job variant of ``POST /evaluation/run``.
         *
         *     A long benchmark (several hundred rows × LLM round-trips) easily
         *     exceeds the proxy's HTTP idle timeout. This endpoint returns
         *     immediately with a job id; the caller polls ``GET /api/v1/jobs/{id}``
         *     until ``status`` is terminal. The actual work is run by the
         *     ``evaluation_run`` handler — see :mod:`app.jobs.handlers`.
         *
         *     The CSV is base64-encoded into the payload so the job table (and the
         *     admin UI) can render the job without holding a file handle, and so
         *     the executor can recover the exact bytes that were submitted.
         */
        post: operations["run_evaluation_async_api_v1_evaluation_run_async_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent background jobs (most recent first) */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single background job — payload + result + error */
        get: operations["get_one_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** In-process metrics snapshot (counters + latency histograms) */
        get: operations["get_metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/prometheus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus text-exposition v0.0.4 of the same metrics */
        get: operations["get_metrics_prometheus_api_v1_metrics_prometheus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classify and extract from a legal query */
        post: operations["analyse_query_api_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream a legal query response token-by-token (SSE)
         * @description SSE variant of POST /api/v1/query.
         *
         *     Reuses the existing orchestration unchanged; emits a `meta` event with
         *     intent/route/confidence/entities/sections, then `token` events, then
         *     `done` (or a terminal `error`).
         *
         *     Analytics: the SSE handler can't easily measure end-to-end latency
         *     from the route (the streamer owns the lifecycle), so we record an
         *     event right after the orchestration's classify-and-resolve step
         *     finishes, before token streaming begins. Generation latency is
         *     already captured in metrics' ``generation_ms`` histogram.
         */
        post: operations["analyse_query_stream_api_v1_query_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminUploadResponse
         * @description Operator-facing response for a corpus upload.
         *
         *     ``status`` is "ingested" on a successful new ingestion (chunks
         *     added to the corpus) or "noop" when the upload was idempotent
         *     against the latest version (same content already on file). 422 is
         *     returned for empty / unparseable files; 415 for unsupported
         *     extensions; 413 for oversized uploads.
         */
        AdminUploadResponse: {
            /** Char Count */
            char_count: number;
            /** Chunks Created */
            chunks_created: number;
            /** Chunks Superseded */
            chunks_superseded: number;
            /** File Size */
            file_size: number;
            /** Is New Version */
            is_new_version: boolean;
            /** Latency Ms */
            latency_ms: number;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Stored As */
            stored_as: string;
            /** Version */
            version: number;
            /** Version Id */
            version_id: string;
            /** Word Count */
            word_count: number;
        };
        /** AnalyticsResponse */
        AnalyticsResponse: {
            /** Intent Distribution */
            intent_distribution: components["schemas"]["IntentCount"][];
            /** Range */
            range: string;
            /** Recent Failures */
            recent_failures: components["schemas"]["FailureEntry"][];
            /** Route Share */
            route_share: {
                [key: string]: number;
            };
            /** Routes */
            routes: string[];
            /** Timeseries */
            timeseries: {
                [key: string]: unknown;
            }[];
            totals: components["schemas"]["AnalyticsTotals"];
        };
        /** AnalyticsTotals */
        AnalyticsTotals: {
            /** Avg Latency Ms */
            avg_latency_ms: number;
            /** Error Rate */
            error_rate: number;
            /** Errors */
            errors: number;
            /** Total */
            total: number;
            /** Window Start */
            window_start: string;
        };
        /**
         * AsyncRunResponse
         * @description Wire shape for the async-run kick-off — small, polling-friendly.
         */
        AsyncRunResponse: {
            job: components["schemas"]["JobOut"];
        };
        /**
         * AuthResponse
         * @description Returned by login / signup / refresh — pairs access token with profile.
         */
        AuthResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            user: components["schemas"]["UserOut"];
        };
        /** Body_run_evaluation_api_v1_evaluation_run_post */
        Body_run_evaluation_api_v1_evaluation_run_post: {
            /**
             * File
             * @description UTF-8 CSV with `question` and `expected_answer` columns
             */
            file: string;
            /**
             * Name
             * @description Optional human label for this run (defaults to filename)
             */
            name?: string | null;
        };
        /** Body_run_evaluation_async_api_v1_evaluation_run_async_post */
        Body_run_evaluation_async_api_v1_evaluation_run_async_post: {
            /**
             * File
             * @description UTF-8 CSV with `question` and `expected_answer` columns
             */
            file: string;
            /**
             * Name
             * @description Optional human label for this run (defaults to filename)
             */
            name?: string | null;
        };
        /** Body_upload_document_api_v1_admin_documents_upload_post */
        Body_upload_document_api_v1_admin_documents_upload_post: {
            /**
             * File
             * @description Corpus document to ingest. Supported: pdf, docx, txt, md, csv, xlsx, png/jpg/jpeg/tiff/tif/bmp/webp (OCR). Max 50 MB.
             */
            file: string;
        };
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /**
             * File
             * @description PDF, DOCX, TXT, CSV, XLSX, PNG, JPG, TIFF, BMP, WEBP — max 50 MB
             */
            file: string;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * CorpusActRow
         * @description Per-act readiness row surfaced on the System Health page.
         */
        CorpusActRow: {
            /** Act Key */
            act_key: string;
            /** Chunk Count */
            chunk_count: number;
            /** Domain */
            domain?: string | null;
            /** Indexed */
            indexed: boolean;
            /** Name */
            name: string;
        };
        /**
         * CorpusStatusBlock
         * @description Live corpus readiness — registered vs indexed acts.
         *
         *     Surfaces drift between the registry (deployment contract) and the
         *     on-disk Chroma index. ``missing_keys`` and ``orphan_keys`` should be
         *     empty under normal operation; non-empty values flag an operator
         *     that re-ingestion is needed.
         */
        CorpusStatusBlock: {
            /** Acts */
            acts: components["schemas"]["CorpusActRow"][];
            /** Indexed Keys */
            indexed_keys: string[];
            /** Missing Keys */
            missing_keys: string[];
            /** Orphan Keys */
            orphan_keys: string[];
            /** Supported Keys */
            supported_keys: string[];
            /** Total Indexed Chunks */
            total_indexed_chunks: number;
        };
        /** CounterEntry */
        CounterEntry: {
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /** Chunks Active */
            chunks_active: number;
            /** Chunks Total */
            chunks_total: number;
            /** Source */
            source: string;
            /** Versions */
            versions: components["schemas"]["DocumentVersionEntry"][];
        };
        /**
         * DocumentItem
         * @description One row in the admin documents table.
         */
        DocumentItem: {
            /** Chunks Active */
            chunks_active: number;
            /** Chunks Total */
            chunks_total: number;
            /** Latest Ingested At */
            latest_ingested_at?: string | null;
            /** Source */
            source: string;
            /** Versions */
            versions: number;
        };
        /** DocumentMetadata */
        DocumentMetadata: {
            /** Char Count */
            char_count: number;
            /** Content Type */
            content_type: string;
            /** File Size */
            file_size: number;
            /** Page Count */
            page_count: number | null;
            /**
             * Parser Extras
             * @default {}
             */
            parser_extras: {
                [key: string]: unknown;
            };
            /** Uploaded At */
            uploaded_at: string;
            /** Word Count */
            word_count: number;
        };
        /** DocumentVersionEntry */
        DocumentVersionEntry: {
            /** Chunk Count */
            chunk_count: number;
            /** Ingested At */
            ingested_at?: string | null;
            /** Superseded */
            superseded: boolean;
            /** Version */
            version: number;
            /** Version Id */
            version_id: string;
        };
        /** DocumentsListResponse */
        DocumentsListResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentItem"][];
            /** Total */
            total: number;
        };
        /** DocumentsSummary */
        DocumentsSummary: {
            /** Chunks Active */
            chunks_active: number;
            /** Chunks Total */
            chunks_total: number;
            /** Total */
            total: number;
        };
        /**
         * EvaluationReport
         * @description Full evaluation response: summary + per-row breakdown.
         */
        EvaluationReport: {
            /** Results */
            results?: components["schemas"]["RowResult"][];
            summary: components["schemas"]["EvaluationSummary"];
        };
        /**
         * EvaluationRunDetail
         * @description Detail view — augments the summary with the persisted report JSON.
         */
        EvaluationRunDetail: {
            /** Cosine Mean */
            cosine_mean: number;
            /** Created At */
            created_at: string;
            /** Created By */
            created_by?: number | null;
            /** Dataset Filename */
            dataset_filename: string;
            /** F1 Mean */
            f1_mean: number;
            /** Failed Rows */
            failed_rows: number;
            /** Id */
            id: number;
            /** Keyword Mean */
            keyword_mean: number;
            /** Name */
            name: string;
            /** Report */
            report: {
                [key: string]: unknown;
            };
            /** Retrieval Mean */
            retrieval_mean: number;
            /** Scored Rows */
            scored_rows: number;
            /** Total Rows */
            total_rows: number;
        };
        /**
         * EvaluationRunSummary
         * @description One row in the evaluation history table.
         */
        EvaluationRunSummary: {
            /** Cosine Mean */
            cosine_mean: number;
            /** Created At */
            created_at: string;
            /** Created By */
            created_by?: number | null;
            /** Dataset Filename */
            dataset_filename: string;
            /** F1 Mean */
            f1_mean: number;
            /** Failed Rows */
            failed_rows: number;
            /** Id */
            id: number;
            /** Keyword Mean */
            keyword_mean: number;
            /** Name */
            name: string;
            /** Retrieval Mean */
            retrieval_mean: number;
            /** Scored Rows */
            scored_rows: number;
            /** Total Rows */
            total_rows: number;
        };
        /** EvaluationRunsListResponse */
        EvaluationRunsListResponse: {
            /** Next Cursor */
            next_cursor?: number | null;
            /** Runs */
            runs: components["schemas"]["EvaluationRunSummary"][];
            /** Total */
            total: number;
        };
        /** EvaluationSummary */
        EvaluationSummary: {
            cosine_similarity: components["schemas"]["MetricSummary"];
            /** Dataset */
            dataset: string;
            f1_score: components["schemas"]["MetricSummary"];
            /** Failed Rows */
            failed_rows: number;
            keyword_overlap: components["schemas"]["MetricSummary"];
            retrieval_confidence: components["schemas"]["MetricSummary"];
            /** Scored Rows */
            scored_rows: number;
            /** Total Rows */
            total_rows: number;
        };
        /** FailureEntry */
        FailureEntry: {
            /** Error Reason */
            error_reason?: string | null;
            /** Intent */
            intent: string;
            /** Query */
            query: string;
            /** Route */
            route: string;
            /** Ts */
            ts: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthCheck
         * @description One named subsystem check (renders as a row in the UI's status banner).
         */
        HealthCheck: {
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Environment */
            environment: string;
            /** Status */
            status: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Version */
            version: string;
        };
        /** IngestionSummary */
        IngestionSummary: {
            /** By Extension */
            by_extension: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /** IntentCount */
        IntentCount: {
            /** Count */
            count: number;
            /** Intent */
            intent: string;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobOut"][];
            /** Total */
            total: number;
        };
        /**
         * JobOut
         * @description Wire shape for one job row.
         *
         *     ``payload`` and ``result`` are decoded on the way out so callers
         *     don't see raw JSON strings.
         */
        JobOut: {
            /** Completed At */
            completed_at?: string | null;
            /** Created At */
            created_at: string | null;
            /** Error */
            error?: string | null;
            /** Id */
            id: number;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["JobStatus"];
            /** Type */
            type: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "completed" | "failed";
        /** LLMProviderInfo */
        LLMProviderInfo: {
            /** Configured */
            configured: boolean;
            /** Model */
            model?: string | null;
            /** Name */
            name: string;
        };
        /** LLMProvidersStatus */
        LLMProvidersStatus: {
            /** Active */
            active: string | null;
            /** Providers */
            providers: components["schemas"]["LLMProviderInfo"][];
        };
        /**
         * LangSmithStatus
         * @description Operator-facing view of LangSmith tracing health.
         *
         *     ``configured`` keeps its existing contract (flag on AND key set);
         *     the broken-out fields below let the System Health page diagnose
         *     "enabled but no key" or "configured but the probe failed".
         *     Connectivity reflects a startup-time reachability check; we don't
         *     re-probe on every /system call. The API key itself is NEVER
         *     serialised — only its presence/absence flag.
         */
        LangSmithStatus: {
            /**
             * Api Key Present
             * @default false
             */
            api_key_present: boolean;
            /** Configured */
            configured: boolean;
            /**
             * Connectivity
             * @default unknown
             */
            connectivity: string;
            /** Connectivity Detail */
            connectivity_detail?: string | null;
            /** Endpoint */
            endpoint?: string | null;
            /** Project */
            project: string;
            /**
             * Tracing Flag Enabled
             * @default false
             */
            tracing_flag_enabled: boolean;
        };
        /** LatencySummary */
        LatencySummary: {
            /** Count */
            count: number;
            /** Mean Ms */
            mean_ms: number;
            /** P50 Ms */
            p50_ms: number;
            /** P95 Ms */
            p95_ms: number;
            /** P99 Ms */
            p99_ms: number;
        };
        /** LegalEntity */
        LegalEntity: {
            /** Confidence */
            confidence: number;
            /** End */
            end: number;
            /** Start */
            start: number;
            /** Type */
            type: string;
            /** Value */
            value: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MemoryStatus */
        MemoryStatus: {
            /** Max Sessions */
            max_sessions: number;
            /** Sessions */
            sessions: number;
            /** Turns Total */
            turns_total: number;
            /** Window */
            window: number;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * MetricSummary
         * @description Mean / min / max of one metric across all scored rows.
         */
        MetricSummary: {
            /** Max */
            max: number;
            /** Mean */
            mean: number;
            /** Min */
            min: number;
        };
        /** OverviewResponse */
        OverviewResponse: {
            documents: components["schemas"]["DocumentsSummary"];
            ingestion: components["schemas"]["IngestionSummary"];
            latency: components["schemas"]["LatencySummary"];
            queries: components["schemas"]["QueriesSummary"];
            /** Uptime Seconds */
            uptime_seconds: number;
            users: components["schemas"]["UsersSummary"];
        };
        /** ProcessStatus */
        ProcessStatus: {
            /** Debug */
            debug: boolean;
            /** Environment */
            environment: string;
            /** Python Version */
            python_version: string;
            /** Uptime Seconds */
            uptime_seconds: number;
        };
        /** QueriesSummary */
        QueriesSummary: {
            /** By Route */
            by_route: {
                [key: string]: number;
            };
            /** Route Share */
            route_share: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
            /**
             * Session Id
             * @description Opaque client session id for multi-turn memory
             */
            session_id?: string | null;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Confidence */
            confidence: number;
            /** Domain */
            domain?: string | null;
            /** Entities */
            entities: components["schemas"]["LegalEntity"][];
            /**
             * Examples
             * @default []
             */
            examples: string[];
            /** Help Text */
            help_text?: string | null;
            /** Intent */
            intent: string;
            /**
             * Next Actions
             * @default []
             */
            next_actions: string[];
            /** Query */
            query: string;
            /** Reason */
            reason: string;
            /**
             * Related Acts
             * @default []
             */
            related_acts: string[];
            /**
             * Retrieved Chunks
             * @default []
             */
            retrieved_chunks: components["schemas"]["RetrievedChunkRecord"][];
            /** Route */
            route: string;
            /**
             * Statute Sections
             * @default []
             */
            statute_sections: components["schemas"]["SectionResult"][];
            /**
             * Suggestions
             * @default []
             */
            suggestions: string[];
        };
        /**
         * RetrievedChunkRecord
         * @description One retrieved-and-reranked chunk surfaced for explainability.
         *
         *     Populated on the RAG path only; deterministic queries do not run
         *     vector retrieval so the list is empty. The full set of stage
         *     scores is optional — older ingestion paths surface only the
         *     `similarity` + `rerank_score` pair, while the hybrid retrieval
         *     pipeline fills in the BM25, fusion, and cross-encoder fields.
         */
        RetrievedChunkRecord: {
            /**
             * Act
             * @default
             */
            act: string;
            /** Bm25 Rank */
            bm25_rank?: number | null;
            /** Bm25 Score */
            bm25_score?: number | null;
            /** Cross Encoder Score */
            cross_encoder_score?: number | null;
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
            /** Fused Rank */
            fused_rank?: number | null;
            /** Fused Score */
            fused_score?: number | null;
            /** Rerank Reason */
            rerank_reason?: string | null;
            /** Rerank Score */
            rerank_score?: number | null;
            /**
             * Section
             * @default
             */
            section: string;
            /** Similarity */
            similarity: number;
            /** Source */
            source: string;
            /** Vector Rank */
            vector_rank?: number | null;
            /** Vector Score */
            vector_score?: number | null;
        };
        /** RootResponse */
        RootResponse: {
            /** Description */
            description: string;
            /** Docs */
            docs: string;
            /** Environment */
            environment: string;
            /** Health */
            health: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /**
         * RowResult
         * @description One evaluated test-set row.
         */
        RowResult: {
            /** Cosine Similarity */
            cosine_similarity: number;
            /** Error */
            error?: string | null;
            /** Expected Answer */
            expected_answer: string;
            /** F1 Score */
            f1_score: number;
            /** Generated Answer */
            generated_answer: string;
            /** Intent */
            intent?: string | null;
            /** Keyword Overlap */
            keyword_overlap: number;
            /** Question */
            question: string;
            /** Retrieval Confidence */
            retrieval_confidence: number;
            /** Route */
            route?: string | null;
        };
        /** SectionResult */
        SectionResult: {
            /** Act */
            act?: string | null;
            /** Citations */
            citations: string[];
            /** Content */
            content: string;
            /** Keywords */
            keywords?: string[];
            /** Number */
            number: string;
            /** Title */
            title: string;
            /**
             * Unit
             * @default section
             */
            unit: string;
        };
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Password */
            password: string;
        };
        /** SystemResponse */
        SystemResponse: {
            /** Checks */
            checks: components["schemas"]["HealthCheck"][];
            corpus: components["schemas"]["CorpusStatusBlock"];
            /** Error Counters */
            error_counters: components["schemas"]["CounterEntry"][];
            /** Ingest Failures */
            ingest_failures: components["schemas"]["CounterEntry"][];
            langsmith: components["schemas"]["LangSmithStatus"];
            llm_providers: components["schemas"]["LLMProvidersStatus"];
            memory: components["schemas"]["MemoryStatus"];
            process: components["schemas"]["ProcessStatus"];
            /** Status */
            status: string;
            vector_store: components["schemas"]["VectorStoreStatus"];
        };
        /** URLIngestRequest */
        URLIngestRequest: {
            /**
             * Persist
             * @description When true, chunk + embed + persist the page into the vector store with version tracking. The page URL is the versioning source identifier.
             * @default false
             */
            persist: boolean;
            /** Url */
            url: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at?: string | null;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "user" | "admin";
        /** UsersSummary */
        UsersSummary: {
            /** Active */
            active: number;
            /** Admins */
            admins: number;
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VectorStoreStatus */
        VectorStoreStatus: {
            /** Collection */
            collection: string;
            /** Count */
            count: number;
            /** Embedding Dim */
            embedding_dim: number;
            /** Path */
            path: string;
        };
        /** VersionedIngestResult */
        VersionedIngestResult: {
            /** Chunks Added */
            chunks_added: number;
            /** Chunks Superseded */
            chunks_superseded: number;
            /** Is New Version */
            is_new_version: boolean;
            /** Source */
            source: string;
            /** Version */
            version: number;
            /** Version Id */
            version_id: string;
        };
        /**
         * _UploadResponse
         * @description Upload response, extended with optional versioning info.
         */
        _UploadResponse: {
            /** Filename */
            filename: string;
            metadata: components["schemas"]["DocumentMetadata"];
            /** Stored As */
            stored_as: string;
            /** Text */
            text: string;
            versioning?: components["schemas"]["VersionedIngestResult"] | null;
        };
        /** _VersionEntry */
        _VersionEntry: {
            /** Chunk Count */
            chunk_count: number;
            /** Ingested At */
            ingested_at?: string | null;
            /** Superseded */
            superseded: boolean;
            /** Version */
            version: number;
            /** Version Id */
            version_id: string;
        };
        /** _VersionsResponse */
        _VersionsResponse: {
            /** Source */
            source: string;
            /** Versions */
            versions: components["schemas"]["_VersionEntry"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootResponse"];
                };
            };
        };
    };
    analytics_api_v1_admin_analytics_get: {
        parameters: {
            query?: {
                /** @description Time window to aggregate over. */
                range?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_admin_documents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_admin_documents_upload_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_admin_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_detail_api_v1_admin_documents__source__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Document source identifier (filename or URL) */
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_admin_documents__source__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Document source identifier */
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluation_runs_api_v1_admin_evaluation_runs_get: {
        parameters: {
            query?: {
                /** @description Cap on the number of rows returned */
                limit?: number;
                /** @description ID-based cursor — pass the previous response's `next_cursor` to fetch the next page. Omit for the first page. */
                cursor?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_run_api_v1_admin_evaluation_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Evaluation run id */
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_evaluation_run_api_v1_admin_evaluation_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Evaluation run id */
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v1_admin_overview_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_health_api_v1_admin_system_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_login_api_v1_auth_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                lf_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                lf_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_url_api_v1_documents_ingest_url_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["URLIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: {
                /** @description When true, chunk + embed + persist the document into the vector store with version tracking. Older revisions of the same source are marked superseded automatically. */
                persist?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_document_versions_api_v1_documents_versions_get: {
        parameters: {
            query: {
                /** @description Document source identifier (filename) */
                source: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_VersionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_evaluation_api_v1_evaluation_run_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_run_evaluation_api_v1_evaluation_run_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_evaluation_async_api_v1_evaluation_run_async_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_run_evaluation_async_api_v1_evaluation_run_async_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                /** @description Cap on the number of rows returned */
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_one_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Job id */
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_prometheus_api_v1_metrics_prometheus_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    /** @example # HELP lawflow_uptime_seconds Process uptime in seconds */
                    "text/plain; version=0.0.4; charset=utf-8": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyse_query_api_v1_query_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyse_query_stream_api_v1_query_stream_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
