"""initial schema

Revision ID: a2b239e819ba
Revises: 
Create Date: 2026-05-20 09:24:14.633292+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a2b239e819ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dataset_filename', sa.String(length=200), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('scored_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('f1_mean', sa.Float(), nullable=False),
    sa.Column('cosine_mean', sa.Float(), nullable=False),
    sa.Column('keyword_mean', sa.Float(), nullable=False),
    sa.Column('retrieval_mean', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_created_by'), ['created_by'], unique=False)

    op.create_table('query_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('route', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('has_error', sa.Boolean(), nullable=False),
    sa.Column('query_preview', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('error_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('query_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_events_intent'), ['intent'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_events_route'), ['route'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_events_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('query_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_query_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_query_events_route'))
        batch_op.drop_index(batch_op.f('ix_query_events_intent'))
        batch_op.drop_index(batch_op.f('ix_query_events_created_at'))

    op.drop_table('query_events')
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_created_by'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_created_at'))

    op.drop_table('evaluation_runs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
